import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import SlideToTheTopButton from './components/SlideToTheTop/SlideToTheTopButton';
import Footer from "./components/Footer/Footer.tsx";

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisi lacus sed viverra tellus in hac habitasse. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. In arcu cursus euismod quis viverra nibh cras. Cursus risus at ultrices mi tempus imperdiet nulla. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Tincidunt eget nullam non nisi. A cras semper auctor neque vitae tempus. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Et tortor at risus viverra. Consectetur lorem donec massa sapien faucibus et molestie ac. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Tincidunt tortor aliquam nulla facilisi. Rhoncus dolor purus non enim praesent. Odio aenean sed adipiscing diam donec adipiscing. Enim sed faucibus turpis in eu mi.
        In iaculis nunc sed augue lacus viverra vitae congue eu. Faucibus vitae aliquet nec ullamcorper sit amet. Cras adipiscing enim eu turpis egestas pretium. Hac habitasse platea dictumst quisque sagittis. Sed ullamcorper morbi tincidunt ornare massa eget. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Sem fringilla ut morbi tincidunt augue. Imperdiet sed euismod nisi porta. Augue neque gravida in fermentum. Dignissim sodales ut eu sem integer vitae justo eget magna. Enim diam vulputate ut pharetra sit amet aliquam. Enim nunc faucibus a pellentesque sit amet. Sodales ut eu sem integer. Sed elementum tempus egestas sed sed risus pretium quam. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Lacinia at quis risus sed vulputate.
        Consectetur adipiscing elit pellentesque habitant. Sed viverra tellus in hac habitasse platea. Tempus urna et pharetra pharetra massa massa ultricies mi quis. Diam maecenas sed enim ut sem viverra aliquet eget. Penatibus et magnis dis parturient montes nascetur ridiculus. Euismod elementum nisi quis eleifend quam adipiscing vitae. Velit sed ullamcorper morbi tincidunt. Cras fermentum odio eu feugiat pretium. Vitae congue eu consequat ac felis donec et odio. Elementum eu facilisis sed odio morbi quis. Tortor vitae purus faucibus ornare suspendisse. Non tellus orci ac auctor augue mauris. Ultricies mi quis hendrerit dolor. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. Lorem dolor sed viverra ipsum nunc aliquet bibendum. Massa sapien faucibus et molestie ac. Habitant morbi tristique senectus et netus et.
        Amet risus nullam eget felis eget nunc. Volutpat diam ut venenatis tellus in metus. Massa id neque aliquam vestibulum. Senectus et netus et malesuada. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Morbi enim nunc faucibus a. Tortor consequat id porta nibh venenatis cras. Felis imperdiet proin fermentum leo vel orci. Fermentum iaculis eu non diam phasellus vestibulum lorem sed risus. Mauris nunc congue nisi vitae suscipit tellus mauris a. Amet consectetur adipiscing elit pellentesque habitant. Interdum velit laoreet id donec ultrices tincidunt. Volutpat commodo sed egestas egestas. Pellentesque adipiscing commodo elit at imperdiet dui. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Id aliquet risus feugiat in ante metus. Convallis a cras semper auctor.
        Ac tortor vitae purus faucibus ornare suspendisse sed. Sit amet commodo nulla facilisi nullam vehicula ipsum. Sollicitudin ac orci phasellus egestas. Lacus sed viverra tellus in hac habitasse platea dictumst. Egestas pretium aenean pharetra magna ac. Lectus mauris ultrices eros in cursus. Sagittis purus sit amet volutpat. Amet nisl suscipit adipiscing bibendum. A erat nam at lectus. Vel turpis nunc eget lorem. Et malesuada fames ac turpis egestas sed tempus. Nam aliquam sem et tortor consequat id porta. Diam vulputate ut pharetra sit amet aliquam id diam. Diam phasellus vestibulum lorem sed risus.
        Eget arcu dictum varius duis at consectetur. Nam at lectus urna duis convallis convallis tellus id interdum. Non enim praesent elementum facilisis leo. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Augue lacus viverra vitae congue eu consequat. Consequat interdum varius sit amet. Commodo odio aenean sed adipiscing diam donec. Diam ut venenatis tellus in metus vulputate eu scelerisque. Elit duis tristique sollicitudin nibh sit amet. Blandit aliquam etiam erat velit scelerisque in. Convallis convallis tellus id interdum velit laoreet. Arcu dui vivamus arcu felis bibendum ut. Malesuada bibendum arcu vitae elementum curabitur vitae. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Praesent semper feugiat nibh sed pulvinar. Morbi non arcu risus quis varius quam. Velit egestas dui id ornare. At consectetur lorem donec massa sapien faucibus et. Non odio euismod lacinia at.
        Nullam vehicula ipsum a arcu cursus vitae. Porttitor lacus luctus accumsan tortor posuere. Pulvinar etiam non quam lacus suspendisse. Aliquam nulla facilisi cras fermentum odio eu feugiat. Nisi porta lorem mollis aliquam ut porttitor. Ac odio tempor orci dapibus ultrices in iaculis. Eleifend donec pretium vulputate sapien nec sagittis aliquam. Ligula ullamcorper malesuada proin libero nunc consequat. Elit ullamcorper dignissim cras tincidunt lobortis. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Tellus molestie nunc non blandit massa enim nec dui. Duis at consectetur lorem donec. Ipsum dolor sit amet consectetur. Tincidunt arcu non sodales neque sodales ut etiam. Non nisi est sit amet facilisis magna etiam. Vitae justo eget magna fermentum iaculis. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Mauris cursus mattis molestie a iaculis at erat pellentesque.
        Quam elementum pulvinar etiam non quam. Sit amet cursus sit amet dictum sit amet. Consequat id porta nibh venenatis cras sed felis eget velit. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Tristique nulla aliquet enim tortor at auctor. Posuere sollicitudin aliquam ultrices sagittis orci a. Lorem ipsum dolor sit amet consectetur adipiscing elit. Cras pulvinar mattis nunc sed blandit. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Pretium lectus quam id leo in vitae turpis massa. Egestas sed sed risus pretium quam vulputate dignissim. Magna sit amet purus gravida. Quis eleifend quam adipiscing vitae proin. Sed libero enim sed faucibus turpis in eu mi bibendum. Dui vivamus arcu felis bibendum ut tristique et egestas. Et magnis dis parturient montes. Rutrum quisque non tellus orci ac. Eget nunc scelerisque viverra mauris. Vitae justo eget magna fermentum iaculis eu non. Ipsum dolor sit amet consectetur adipiscing elit.
        Sed lectus vestibulum mattis ullamcorper. Elit at imperdiet dui accumsan. Lacinia at quis risus sed vulputate odio ut. Et tortor consequat id porta nibh. Felis donec et odio pellentesque diam volutpat commodo sed. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Amet dictum sit amet justo donec enim diam vulputate. Nibh tortor id aliquet lectus. Volutpat est velit egestas dui id ornare. Sed ullamcorper morbi tincidunt ornare massa eget. Ut tristique et egestas quis ipsum.
        Egestas tellus rutrum tellus pellentesque. In nulla posuere sollicitudin aliquam ultrices. In pellentesque massa placerat duis ultricies lacus. Mauris pharetra et ultrices neque ornare aenean euismod elementum. Et malesuada fames ac turpis egestas. Consectetur libero id faucibus nisl tincidunt eget nullam non. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Purus semper eget duis at. Auctor neque vitae tempus quam. Egestas maecenas pharetra convallis posuere morbi leo urna. Libero justo laoreet sit amet cursus. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Cursus sit amet dictum sit amet justo. In iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit amet mattis vulputate.
        Nascetur ridiculus mus mauris vitae ultricies leo. Consectetur libero id faucibus nisl tincidunt eget nullam non. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Gravida dictum fusce ut placerat. At varius vel pharetra vel turpis. A pellentesque sit amet porttitor eget dolor morbi non. Tristique et egestas quis ipsum suspendisse ultrices gravida. Facilisis gravida neque convallis a. Donec et odio pellentesque diam volutpat commodo. Bibendum arcu vitae elementum curabitur vitae. Enim sed faucibus turpis in eu mi bibendum neque egestas.
        Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Purus ut faucibus pulvinar elementum integer enim. Vel eros donec ac odio tempor orci dapibus. Arcu risus quis varius quam. Elementum nibh tellus molestie nunc. Sed libero enim sed faucibus turpis in eu mi bibendum. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Ac ut consequat semper viverra nam libero justo laoreet. Velit euismod in pellentesque massa placerat duis. Purus sit amet luctus venenatis. Neque ornare aenean euismod elementum nisi quis eleifend. Faucibus et molestie ac feugiat sed lectus vestibulum mattis. Consequat nisl vel pretium lectus quam. Gravida cum sociis natoque penatibus et magnis. Ipsum consequat nisl vel pretium lectus quam id. Convallis aenean et tortor at risus viverra adipiscing at. Sit amet massa vitae tortor condimentum. Semper auctor neque vitae tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada. Urna et pharetra pharetra massa massa ultricies.
        Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Ullamcorper a lacus vestibulum sed arcu non odio. Lectus mauris ultrices eros in cursus. Commodo elit at imperdiet dui. Penatibus et magnis dis parturient montes nascetur. Et leo duis ut diam quam nulla porttitor massa. Tristique senectus et netus et malesuada fames. Nunc sed blandit libero volutpat. Tempus urna et pharetra pharetra. Phasellus vestibulum lorem sed risus. Vitae semper quis lectus nulla at volutpat diam. Risus ultricies tristique nulla aliquet enim tortor at auctor. Eget arcu dictum varius duis at consectetur lorem.
        Suscipit adipiscing bibendum est ultricies integer quis. Orci ac auctor augue mauris augue neque gravida. Condimentum vitae sapien pellentesque habitant. Suscipit tellus mauris a diam. Ut etiam sit amet nisl purus in mollis. Viverra orci sagittis eu volutpat odio facilisis mauris sit amet. Semper viverra nam libero justo laoreet sit amet cursus. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Lectus quam id leo in vitae turpis. In massa tempor nec feugiat nisl. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Auctor neque vitae tempus quam pellentesque nec nam. Egestas tellus rutrum tellus pellentesque eu tincidunt. At auctor urna nunc id cursus metus aliquam. Purus semper eget duis at tellus at urna. Tellus elementum sagittis vitae et leo duis. Blandit libero volutpat sed cras.
        Facilisis mauris sit amet massa vitae tortor condimentum. Scelerisque purus semper eget duis at tellus at. Nisi lacus sed viverra tellus in hac habitasse. Mauris nunc congue nisi vitae suscipit tellus mauris a. Consectetur adipiscing elit duis tristique sollicitudin. Gravida quis blandit turpis cursus in. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Cursus metus aliquam eleifend mi in. Quis commodo odio aenean sed adipiscing diam. Nibh nisl condimentum id venenatis a condimentum. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. In dictum non consectetur a. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Vitae suscipit tellus mauris a diam maecenas sed. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Lorem donec massa sapien faucibus et molestie ac. Vitae semper quis lectus nulla at volutpat diam. Vitae congue mauris rhoncus aenean vel.</p>
      <SlideToTheTopButton></SlideToTheTopButton>
      <Footer />
    </>
  )
}

export default App
